#!/usr/bin/env bash
# Automated server setup for Rio Coffee (riocoffee.in)
# Installs Nginx, certbot, obtains TLS certs, configures HTTPS proxy, and opens firewall
# 
# Usage: sudo ./scripts/setup-server.sh
# Assumes: Ubuntu/Debian, systemd, ufw, and that rio-coffee app is running on localhost:3000
#
# Steps performed:
# 1. Verify the app is running on port 3000
# 2. Update system packages
# 3. Install Nginx and certbot
# 4. Configure Nginx as reverse proxy for riocoffee.in + www.riocoffee.in
# 5. Obtain Let's Encrypt certificate
# 6. Open firewall ports 80 and 443
# 7. Enable and start Nginx
# 8. Verify HTTPS

set -euo pipefail

DOMAIN="riocoffee.in"
WWW_DOMAIN="www.riocoffee.in"
APP_PORT=3000
NGINX_SITE="/etc/nginx/sites-available/riocoffee"
NGINX_ENABLED="/etc/nginx/sites-enabled/riocoffee"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

error() {
  echo "[ERROR] $*" >&2
  exit 1
}

# 1. Verify app is running on port 3000
log "Step 1: Verifying app is running on port $APP_PORT..."
if ! netstat -tln 2>/dev/null | grep -q ":$APP_PORT "; then
  error "Port $APP_PORT is not listening. Start the app first: 'npx next start -p $APP_PORT' or via systemd service."
fi
log "✓ App is listening on port $APP_PORT"

# 2. Update system packages
log "Step 2: Updating system packages..."
apt-get update -qq
apt-get upgrade -y -qq
log "✓ Packages updated"

# 3. Install Nginx and certbot
log "Step 3: Installing Nginx and certbot..."
apt-get install -y -qq nginx certbot python3-certbot-nginx ufw
log "✓ Nginx and certbot installed"

# 4. Configure Nginx as reverse proxy
log "Step 4: Configuring Nginx for $DOMAIN and $WWW_DOMAIN..."
cat > "$NGINX_SITE" <<'EOF'
# Rio Coffee Reverse Proxy Configuration
# Proxies HTTP/HTTPS traffic to localhost:3000

server {
    listen 80;
    listen [::]:80;
    server_name riocoffee.in www.riocoffee.in;

    # Redirect HTTP to HTTPS
    location / {
        return 301 https://$host$request_uri;
    }

    # Allow certbot ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name riocoffee.in www.riocoffee.in;

    # SSL certificates (will be generated by certbot)
    ssl_certificate /etc/letsencrypt/live/riocoffee.in/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/riocoffee.in/privkey.pem;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header Referrer-Policy no-referrer-when-downgrade;
    add_header Permissions-Policy "geolocation=(), microphone=(), camera=()";

    # Proxy to Next.js app
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_buffering off;
    }

    # Static files (if needed)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://127.0.0.1:3000;
        proxy_cache_valid 200 10d;
        add_header Cache-Control "public, immutable";
    }
}
EOF
log "✓ Nginx config created at $NGINX_SITE"

# Enable the site
if [ -L "$NGINX_ENABLED" ]; then
  rm "$NGINX_ENABLED"
fi
ln -s "$NGINX_SITE" "$NGINX_ENABLED"
log "✓ Site enabled"

# Test Nginx config
if ! nginx -t >/dev/null 2>&1; then
  error "Nginx config test failed. Check $NGINX_SITE for errors."
fi
log "✓ Nginx config is valid"

# 5. Obtain Let's Encrypt certificate
log "Step 5: Obtaining Let's Encrypt certificate for $DOMAIN and $WWW_DOMAIN..."
mkdir -p /var/www/certbot
if [ ! -d "/etc/letsencrypt/live/$DOMAIN" ]; then
  certbot certonly --webroot -w /var/www/certbot -d "$DOMAIN" -d "$WWW_DOMAIN" --non-interactive --agree-tos --email admin@"$DOMAIN" 2>&1 | grep -v "^Saving debug log to" || true
  log "✓ Certificate obtained"
else
  log "✓ Certificate already exists for $DOMAIN"
fi

# Reload Nginx to use certs
log "Reloading Nginx with certificates..."
systemctl reload nginx
log "✓ Nginx reloaded"

# 6. Open firewall ports 80 and 443
log "Step 6: Configuring firewall..."
ufw default deny incoming >/dev/null 2>&1 || true
ufw default allow outgoing >/dev/null 2>&1 || true
ufw allow 22/tcp >/dev/null 2>&1 || true  # SSH
ufw allow 80/tcp >/dev/null 2>&1 || true  # HTTP
ufw allow 443/tcp >/dev/null 2>&1 || true # HTTPS
ufw --force enable >/dev/null 2>&1 || true
log "✓ Firewall configured: ports 22, 80, 443 allowed"

# 7. Enable and start Nginx
log "Step 7: Enabling and starting Nginx..."
systemctl enable nginx >/dev/null 2>&1
systemctl restart nginx
log "✓ Nginx enabled and restarted"

# 8. Verify HTTPS
log "Step 8: Verifying HTTPS setup..."
sleep 2
if curl -s -o /dev/null -w "%{http_code}" "https://$DOMAIN" | grep -q "200\|301\|302"; then
  log "✓ HTTPS is working! Visit https://$DOMAIN"
else
  log "⚠ Could not verify HTTPS (might be firewall issue or DNS propagation delay)"
fi

# Setup auto-renewal
log "Setting up certificate auto-renewal..."
systemctl enable certbot.timer >/dev/null 2>&1 || systemctl enable certbot.service >/dev/null 2>&1
systemctl start certbot.timer >/dev/null 2>&1 || true
log "✓ Auto-renewal configured"

log ""
log "=========================================="
log "✓ Server setup complete!"
log "=========================================="
log "Your site should now be accessible at:"
log "  https://$DOMAIN"
log "  https://$WWW_DOMAIN"
log ""
log "Next steps:"
log "1. Verify your DNS A records point to this server's IP"
log "2. Test: curl https://$DOMAIN"
log "3. Check logs: tail -f /var/log/nginx/access.log"
log "4. Next.js app must stay running on port 3000"
log ""
log "To monitor certificates:"
log "  certbot certificates"
log ""
log "To renew certificates manually:"
log "  certbot renew --force-renewal"
log ""
